# ---------------------------------------------------
# NullBrand Configuration
# Lightweight MOTD system
# ---------------------------------------------------

# Enables debug logging
debug: false

# ---------------------------------------------------
# MOTD SETTINGS
# ---------------------------------------------------
motd:

  # Enable MOTD control
  enabled: true

  # Active profile
  profile: "default"

  # Favicon file inside /plugins/NullBrand/favicons/
  favicon: "test.png"



# ---------------------------------------------------
# MOTD PROFILES
# ---------------------------------------------------
# NOTE: Hover will only work on Proxies, and it does not support HEX Colors!

profiles:

  # Global fallback profile
  global:
    lines:
      - "&7Welcome to our server"
      - "&fHave fun!"

  # Default server MOTD
  default:
    lines:
      - "&5Null&dBrand"
      - "&7This is line 2"
    hover:
      enabled: false
      lines:
        - "&7Welcome to &5Null&dBrand"
        - "&7Running powerful infrastructure"

  # Example event profile
  event:
    lines:
      - "&6Special Event Live!"
      - "&eJoin today!"
    hover:
      enabled: true
      lines:
        - "&6Limited time event"
        - "&eDon't miss it!"
